matrix:
  include:
    - language: python
      python: 3.6
      services:
  	- mongodb
      before_install:
	- python3 bin/resetDatabase.py
        - cd api
      install:
        - pip3 install -r requirements.txt
      before_script:
  	- sleep 15
  	- mongo mydb_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
      script:
        - python3 tests.py

    - language: node_js
      node_js: node
      before_install:
        - cd sfja
      install:
        - yarn
      script:
        - yarn run lint
