matrix:
  include:
    - language: python
      python: 3.6
      before_install:
        - cd api
      install:
        - pip3 install -r requirements.txt
      script:
        - python3 tests.py

    - language: node_js
      node_js: node
      before_install:
        - cd sfja
      install:
        - yarn
      script:
        - yarn run lint .
